server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api

users-service:
      # bcrypt hashed password: $2a$10$tSepBpJKxkvJnkNR45miqO/c55NLFw49YWx9Z6jqZzHkxwbvkMI3i
  encryption-key: ${ENCRYPT_KEY:gd3jMu1Asdr/9mrQ+Pdvgo1K9tO10n7hu6StlRpDd94=} # base64 key
  hashSecret: ${HASH_SECRET:9s4gZDGFUESlt7+96NEyDasV22OQFSoD9H32f2bS7fo=} # base64 recommended
  keycloak:
    url: ${KEYCLOAK_URL:http://localhost:8080}
    master-realm: master
    admin-client-id: admin-cli
    username: admin
    password: Itest@ke2
    realm : retail-flow

spring:

  application.name: users-service
  main:
    banner-mode: off
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  profiles:
    active: local

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/retail-flow
          jwk-set-uri: http://localhost:8080/realms/retail-flow/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: frontend-app          # ← from your Keycloak client (public client!)
            client-secret: ""                       # ← empty for public client (PKCE)
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid,profile,email,roles       # add 'roles' if you map realm/client roles

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/retail-flow   # ← your realm!
            user-name-attribute: preferred_username


  ############################### Database ############################

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=users_schema}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        type:
          contributors: org.springframework.data.jpa.repository.config.BeanContainerBeanFactoryAdvisingBeanPostProcessor

  #  jpa.show-sql: true

  # ref: https://contribute.liquibase.com/extensions-integrations/directory/integration-docs/springboot/configuration/
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
  #   rollback-file: rollback.sql

logging:
  level:
    liquibase: DEBUG
